<?php

namespace TermBundle\Repository;

/**
 * termRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class termRepository extends \Doctrine\ORM\EntityRepository
{
}
