<?php

namespace AppBundle\Repository;

/**
 * CauseAssignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CauseAssignRepository extends \Doctrine\ORM\EntityRepository
{
}
