<?php

namespace AppBundle\Repository;

/**
 * szRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class szRepository extends \Doctrine\ORM\EntityRepository
{
   
}
