<?php

namespace AppBundle\Repository;

/**
 * theEndDecisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class theEndDecisionRepository extends \Doctrine\ORM\EntityRepository
{
}
